### ISSUE TITLE
DfnsApiClient behind Proxy

### ISSUE THREAD

**Issue by darloetsc** [dfns/dfns-sdk-ts#70]
Hey Guys,

I cannot get the DfnsApiClient to work with a reverse proxy, the baseUrl configuration seems to cut off any extension behind the hostname. Based on the example i tried to configure the init as following:

```typescript
export const dfnsApi = (): DfnsApiClient => {
  const signer = new WebAuthn({ rpId: 'localhost' })
  const baseUrl = window.location.origin + "/dfns-proxy";
  return new DfnsApiClient({
    appId: 'ap-blub',
    authToken: localStorage.getItem('DFNS_AUTH_TOKEN') ?? undefined,
    baseUrl: baseUrl,
    signer,
  })
}
```
However, the request strips out the /dfns-proxy and still fires:

`http://localhost:4200/auth/action/init`

instead of the expected:

`http://localhost:4200/dfns-proxy/auth/action/init`

In the sdk, the url is constructed based on the URL Object:

```typescript
const fullUrl = <T extends DfnsBaseApiOptions>(fetch: Fetch<T>): Fetch<T> => {
  return async (resource, options) => {
    const { baseUrl } = options.apiOptions
    resource = new URL(resource, baseUrl)
    return fetch(resource, options)
  }
}
```
This seems to cut off any trailing path.

Would be awesome to have a way to run the client-side sdk with a proxy config to prevent direct calls to the dfns api. This would allow for a lazy guy setup, where only the minimum like registration is done in a delegated fashion, and everything else can be handled by the client.

**Comment by djin-dfns** [comment]
@darloetsc can you try to end your base url with a `/`. I believe that should fix your issue based on my testing.

```
const baseUrl = window.location.origin + "/dfns-proxy/";
```
